const cf_handles = {
  '苍响': ['Toxel', 'chielo', 'Prime21'],
  '试炼者': ['Max.D.', 'Hardict', 'SANJIN'],
  '我不知道.png': ['Potassium_', 'qxforever', 'tyakennikku'],
  '仰望星空': ['ws_zzyer', 'Immortal.S', 's_h_y'],
  '未闻WA': ['TownYang', 'Kevin00', 'zhtjtcz'],
  '从爆零开始的ACM生活': ['lyuankai', 'kipple', 'holmium01'],
  '将来我一定比你聪明比你强': ['infinity37', 'Zars19', '_wzx27'],
  '大吉大利，今晚吃 mian();': ['pantw', 'Devil_G', 'withinlover'],
  '奔跑的小菜鸡': ['Random_chen', 'rising0321', 'selia'],
  '铲车人': ['FYH_SSGSS', 'wxg', 'Mychael'],
  '辉夜大小姐想让我AC': ['2sozx', 'Bazoka13', 'JJLeo'],
  '火锅队': ['L_RUA', 'aspirine', 'MisakaTao'],
  '合法字符串': ['qgjyf2001', 'jxm2001', 'lgwza'],
  '路人队伍的养成方法': ['Intouchables', 'iuiou', 'QuantumBolt'],
  '我们不会起名': ['great_designer', 'kongyoubuaa', 'BH18376359'],
  '地址过低': ['dragonylee', 'cnMember', 'hujin'],
  '周末早上请不要训练': ['NoMansLand', 'fayy', 'duancheng'],
  '普通攻击是WA而且触发TLE还能RE的弟弟你喜欢吗': ['Jerydeak', 'Dr_nobody'],
  '从前往后做': ['YUKI_LELOUCH', 'wzy2001wzy', 'FarmerThy'],
  '神奈川冲浪里': ['airbust', 'kazamori', 'ket98']
};
