const cf_handles = {
    '苍响': ['Toxel', 'chielo', 'Prime21'],
    '试炼者': ['Max.D.', 'Hardict', 'SANJIN'],
    '我不知道.png': ['Potassium_', 'qxforever', 'tyakennikku'],
    '仰望星空': ['ws_zzyer', 'Immortal.S', 's_h_y'],
    '未闻WA': ['TownYang', 'Kevin00', 'zhtjtcz'],
    '从爆零开始的ACM生活': ['lyuankai', 'kipple', 'holmium01'],
    '将来我一定比你聪明比你强': ['infinity37', 'Zars19', '_wzx27'],
    '大吉大利，今晚吃 mian();': ['pantw', 'Devil_G', 'withinlover'],
    '奔跑的小菜鸡': ['Random_chen', 'rising0321', 'selia'],
    '铲车人': ['FYH_SSGSS', 'wxg', 'Mychael'],
    '辉夜大小姐想让我AC': ['2sozx', 'Bazoka13', 'JJLeo'],
    '火锅队': ['L_RUA', 'aspirine', 'MisakaTao'],
    '合法字符串': ['qgjyf2001', 'jxm2001', 'lgwza'],
    '路人队伍的养成方法': ['Intouchables', 'iuiou', 'QuantumBolt'],
    '我们不会起名': ['great_designer', 'kongyoubuaa', 'BH18376359'],
    '地址过低': ['dragonylee', 'cnMember', 'hujin'],
    '周末早上请不要训练': ['NoMansLand', 'fayy', 'duancheng'],
    '普通攻击是WA而且触发TLE还能RE的弟弟你喜欢吗': ['JeryDeak', 'Dr_nobody'],
    '从前往后做': ['YUKI_LELOUCH', 'wzy2001wzy', 'FarmerThy'],
    '神奈川冲浪里': ['airbust', 'Kazamori', 'Ket98'],
};

const atcoder_handles = {
    '苍响': ['zhongzihao', 'chielo', 'prime21'],
    '试炼者': ['maxdumbledore', 'Hardict', 'Atlantis592'],
    '我不知道.png': ['PotassiumWings', 'qxforever', 'nikkukun'],
    '仰望星空': ['ws_zzyer', 'x342333349', 'shyakocat'],
    '未闻WA': ['TownYan', 'Marvolo'],
    '从爆零开始的ACM生活': ['liyuankai', 'kipple', 'holmium_jwh'],
    '将来我一定比你聪明比你强': ['infinity37', 'Zars19', 'Craddy'],
    '大吉大利，今晚吃 mian();': ['minamikotori', 'Devil_Gary', 'withinlover'],
    '奔跑的小菜鸡': ['Rchen', 'yyxzhj', 'selia'],
    '铲车人': ['FYHSSGSS', 'wxgwxg', 'Mychael'],
    '辉夜大小姐想让我AC': ['shjzhqm', 'Bazoka13', 'JJLeo'],
    '火锅队': ['L_RUA', 'aspirine', 'MisakaTao'],
    '合法字符串': ['lgwza'],
    '路人队伍的养成方法': ['iuiou', 'QuantumBolt'],
    '我们不会起名': ['kongyoubuaa', 'serein'],
    '地址过低': ['dragonylee', 'Member22335', 'hujin'],
    '周末早上请不要训练': ['sharco'],
    '普通攻击是WA而且触发TLE还能RE的弟弟你喜欢吗': ['gobegobe'],
    '从前往后做': ['YUKILSY', 'wzy2001wzy'],
    '神奈川冲浪里': ['airbust', 'kazamori', 'K98'],
};
